---
name: dataanalyst
description: Data Analyst
runtime:
  name: python
  options:
    toolchain: uv
config:
  pulumi:tags:
    value:
      pulumi:template: python
  datarobot:tracecontext: dataanalyst
